sudo: false
language: go

go:
  - 1.9
  - "1.10"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - cd reader
  - go fmt
  - go test
  #- cd ..
  #- cd cmd/go-reader
  #- go fmt
  #- go test
  - go build
